### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by elie222** [mattkrick/meatier#12]
I get the following error after running `npm install`:
```
1431 error Darwin 15.0.0
1432 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
1433 error node v4.2.3
1434 error npm  v2.14.7
1435 error code EPEERINVALID
1436 error peerinvalid The package webpack@2.0.1-beta does not satisfy its siblings' peerDependencies requirements!
1436 error peerinvalid Peer babel-loader@6.2.0 wants webpack@^1.0.0
1436 error peerinvalid Peer extract-text-webpack-plugin@0.9.1 wants webpack@^1.9.11
1436 error peerinvalid Peer webpack-dev-middleware@1.4.0 wants webpack@>=1.0.0 <3
1437 verbose exit [ 1, true ]
```

Any ideas why?

**Comment by mattkrick** [comment]
You *should* be able to ignore those peerDeps. I think that peerDeps throw errors in npm2, but warnings in npm3. When you run the build, do you get any error messages?

**Comment by elie222** [comment]
I posted the error messages above. What do you mean?

**Comment by mattkrick** [comment]
thats the error message for running npm install. is there an error message for running `npm run build` or `npm run start`?

**Comment by Valentin-Seehausen** [comment]
I get the same:
```
npm WARN EPEERINVALID babel-loader@6.2.0 requires a peer of webpack@^1.0.0 but none was installed.

npm WARN EPEERINVALID extract-text-webpack-plugin@0.9.1 requires a peer of webpack@^1.9.11  but none was installed.

npm WARN EPEERINVALID webpack-dev-middleware@1.4.0 requires a peer of webpack@>=1.0.0 <3 but none was installed.```

**Comment by Valentin-Seehausen** [comment]
and after npm run build:

```
> meatier@0.5.0 build /media/valentin/Development/Tests/meatier
> npm run build:client && npm run build:server


> meatier@0.5.0 build:client /media/valentin/Development/Tests/meatier
> rimraf build && NODE_ENV=production webpack --progress --colors --config ./webpack/prod.babel.js

Hash: 0a20016fb18ee87fd0bf  
Version: webpack 2.0.1-beta
Time: 19293ms
 [914] multi app 40 bytes {1} [built]
    + 1083 hidden modules

ERROR in ./universal/routes/login.js
Module not found: Error: Cannot resolve module 'universal/components/LostPassword/LostPassword' in /media/valentin/Development/Tests/meatier/src/universal/routes
 @ ./universal/routes/login.js 54:27-90

ERROR in ./universal/components/Lane/Lane.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./Lane.css in /media/valentin/Development/Tests/meatier/src/universal/components/Lane
 @ ./universal/components/Lane/Lane.js 26:12-33

ERROR in chunk app [entry]
0.0a20016fb18ee87fd0bf.js
Cannot read property 'id' of null
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 3 hidden modules
Child extract-text-webpack-plugin:
        + 4 hidden modules

npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:client"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! meatier@0.5.0 build:client: `rimraf build && NODE_ENV=production webpack --progress --colors --config ./webpack/prod.babel.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the meatier@0.5.0 build:client script 'rimraf build && NODE_ENV=production webpack --progress --colors --config ./webpack/prod.babel.js'.
npm ERR! This is most likely a problem with the meatier package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf build && NODE_ENV=production webpack --progress --colors --config ./webpack/prod.babel.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls meatier
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/valentin/Development/Tests/meatier/npm-debug.log

npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! meatier@0.5.0 build: `npm run build:client && npm run build:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meatier@0.5.0 build script 'npm run build:client && npm run build:server'.
npm ERR! This is most likely a problem with the meatier package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:client && npm run build:server
npm ERR! You can get their info via:
npm ERR!     npm owner ls meatier
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/valentin/Development/Tests/meatier/npm-debug.log
```

**Comment by mattkrick** [comment]
those are just warnings, feel free to ignore

**Comment by Valentin-Seehausen** [comment]
Ah ok. Just thought I should install webpack @2? Its beta?

BTW: Yeah yeah, great idea, keep on going. I am really interesting in how many stars your repo has in one week!

**Comment by Valentin-Seehausen** [comment]
On npm run, this is also ok? 

```

1450374364830 - Origin: Worker (PID 27307)
   [Error] Error: Cannot find module '../../serverBuild/app.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/media/valentin/Development/Tests/meatier/src/server/createSSR.js:27:12)
    at Module._compile (module.js:425:26)
    at loader (/media/valentin/Development/Tests/meatier/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/media/valentin/Development/Tests/meatier/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
1450374364928 - Worker 0 exited - Exit code: 0

**Comment by mattkrick** [comment]
you'll want to run `npm run build` first. i'll add a workaround later today.

**Comment by Valentin-Seehausen** [comment]
I did, but I get some errors, that I posted above.

**Comment by mattkrick** [comment]
in your terminal type `npm run build && npm start`. Does it throw an error?

**Comment by Valentin-Seehausen** [comment]
Jap.
```
npm run build && npm start

> meatier@0.5.0 build /media/valentin/Development/Tests/meatier
> npm run build:client && npm run build:server


> meatier@0.5.0 build:client /media/valentin/Development/Tests/meatier
> rimraf build && NODE_ENV=production webpack --progress --colors --config ./webpack/prod.babel.js

Hash: 0a20016fb18ee87fd0bf  
Version: webpack 2.0.1-beta
Time: 24438ms
 [914] multi app 40 bytes {1} [built]
    + 1083 hidden modules

ERROR in ./universal/routes/login.js
Module not found: Error: Cannot resolve module 'universal/components/LostPassword/LostPassword' in /media/valentin/Development/Tests/meatier/src/universal/routes
 @ ./universal/routes/login.js 54:27-90

ERROR in ./universal/components/Lane/Lane.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./Lane.css in /media/valentin/Development/Tests/meatier/src/universal/components/Lane
 @ ./universal/components/Lane/Lane.js 26:12-33

ERROR in chunk app [entry]
0.0a20016fb18ee87fd0bf.js
Cannot read property 'id' of null
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 3 hidden modules
Child extract-text-webpack-plugin:
        + 4 hidden modules

npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:client"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! meatier@0.5.0 build:client: `rimraf build && NODE_ENV=production webpack --progress --colors --config ./webpack/prod.babel.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the meatier@0.5.0 build:client script 'rimraf build && NODE_ENV=production webpack --progress --colors --config ./webpack/prod.babel.js'.
npm ERR! This is most likely a problem with the meatier package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf build && NODE_ENV=production webpack --progress --colors --config ./webpack/prod.babel.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls meatier
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/valentin/Development/Tests/meatier/npm-debug.log

npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! meatier@0.5.0 build: `npm run build:client && npm run build:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meatier@0.5.0 build script 'npm run build:client && npm run build:server'.
npm ERR! This is most likely a problem with the meatier package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:client && npm run build:server
npm ERR! You can get their info via:
npm ERR!     npm owner ls meatier
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/valentin/Development/Tests/meatier/npm-debug.log
```

**Comment by mattkrick** [comment]
now that is really bizarre.... did you delete your node_modules after you upgraded to node 5?

**Comment by Valentin-Seehausen** [comment]
I think it could have somethink to do with webpack, because after `npm install` it says 
```
npm WARN EPEERINVALID babel-loader@6.2.0 requires a peer of webpack@^1.0.0 but none was installed.
npm WARN EPEERINVALID extract-text-webpack-plugin@0.9.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN EPEERINVALID webpack-dev-middleware@1.4.0 requires a peer of webpack@>=1.0.0 <3 but none was installed.
```
but `webpack` is at 2.0.1-beta...

Ok, node_modules where should I delete it?

**Comment by Valentin-Seehausen** [comment]
Deleted it from my personal folder. Problem remains.

(Sorry if I am silly. Thanks for your help!)

**Comment by mattkrick** [comment]
i have those warnings too, that's OK. it's because an npm package ending with `-xxx` doesn't satisfy peerDeps. Delete your whole node_modules folder & npm i

**Comment by Valentin-Seehausen** [comment]
argh. no. deleted the node_modules from meatier and did npm i and npm run build, still the same errors.

**Comment by Valentin-Seehausen** [comment]
npm start outputs this frequently:
```
1450376393227 - Origin: Worker (PID 2987)
   [Error] Error: Cannot find module '../../serverBuild/app.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/media/valentin/Development/Tests/meatier/src/server/createSSR.js:27:12)
    at Module._compile (module.js:425:26)
    at loader (/media/valentin/Development/Tests/meatier/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/media/valentin/Development/Tests/meatier/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
1450376393340 - Worker 0 exited - Exit code: 0
```

**Comment by mattkrick** [comment]
k, got rid of the build step. pull the new version & just run `npm start`. let me know if it's still throwing

**Comment by Valentin-Seehausen** [comment]
updated npm in the same time. wasnt helping.

**Comment by mattkrick** [comment]
yeah, npm3 is kinda a drag. i waited until 3.5.2 thinking that's enough time to work out the kinks. nope. let me know how the new install goes (it'll probably take about 15 mins with npm3)

**Comment by Valentin-Seehausen** [comment]
Starting great, but then exiting with more then 1000 lines, could only get the last ones:
```
 [1024] ./~/react/lib/ReactComponentWithPureRenderMixin.js 1.51 kB {0} {3} [built]
 [1025] ./~/react/lib/ReactFragment.js 2.54 kB {0} {3} [built]
 [1026] ./~/react/lib/ReactTransitionChildMapping.js 3.14 kB {0} {3} [built]
 [1027] ./~/react/lib/ReactTransitionGroup.js 6.14 kB {0} {3} [built]
 [1028] ./~/react/lib/shallowCompare.js 694 bytes {0} {3} [built]
 [1105] ./src/universal/components/ResetPassword/ResetPassword.css 1.33 kB {3} [built]
chunk    {4} 4.2a318991f8410eebe4b1.js 11.6 kB {1} [rendered]
  [958] ./src/universal/containers/VerifyEmail/VerifyEmailContainer.js 5.53 kB {4} [built]
  [984] ./~/css-loader?modules&importLoaders=1&localIdentName=[name].[local].[hash:base64:5]!./~/postcss-loader!./src/universal/components/VerifyEmail/VerifyEmail.css 476 bytes {4} [built]
 [1047] ./src/universal/components/VerifyEmail/VerifyEmail.js 4.28 kB {4} [built]
 [1107] ./src/universal/components/VerifyEmail/VerifyEmail.css 1.32 kB {4} [built]
chunk    {5} 5.2a318991f8410eebe4b1.js 5.94 kB {1} [rendered]
  [956] ./src/universal/components/ResetPasswordSuccess/ResetPasswordSuccess.js 4.08 kB {5} [built]
  [983] ./~/css-loader?modules&importLoaders=1&localIdentName=[name].[local].[hash:base64:5]!./~/postcss-loader!./src/universal/components/ResetPasswordSuccess/ResetPasswordSuccess.css 512 bytes {5} [built]
 [1106] ./src/universal/components/ResetPasswordSuccess/ResetPasswordSuccess.css 1.35 kB {5} [built]
chunk    {6} 6.2a318991f8410eebe4b1.js 5.81 kB {1} [rendered]
  [954] ./src/universal/components/ResetEmailSent/ResetEmailSent.js 3.96 kB {6} [built]
  [981] ./~/css-loader?modules&importLoaders=1&localIdentName=[name].[local].[hash:base64:5]!./~/postcss-loader!./src/universal/components/ResetEmailSent/ResetEmailSent.css 518 bytes {6} [built]
 [1104] ./src/universal/components/ResetEmailSent/ResetEmailSent.css 1.33 kB {6} [built]
chunk    {7} 7.2a318991f8410eebe4b1.js 3.49 kB {1} [rendered]
  [953] ./src/universal/components/NotFound/NotFound.js 3.49 kB {7} [built]
chunk    {8} 8.2a318991f8410eebe4b1.js 3.77 kB {1} [rendered]
  [952] ./src/universal/components/Logout/Logout.js 3.77 kB {8} [built]

ERROR in ./src/universal/routes/login.js
Module not found: Error: Cannot resolve module 'universal/components/LostPassword/LostPassword' in /media/valentin/Development/Tests/meatier/src/universal/routes
 @ ./src/universal/routes/login.js 54:27-90

ERROR in ./src/universal/components/Lane/Lane.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./Lane.css in /media/valentin/Development/Tests/meatier/src/universal/components/Lane
 @ ./src/universal/components/Lane/Lane.js 37:12-33

ERROR in chunk app [entry]
0.2a318991f8410eebe4b1.js
Cannot read property 'id' of null
```

**Comment by mattkrick** [comment]
make sure webpack is not installed globally. maybe webpack-2 isn't playing well with linux? try playing with the `context` in the config. I know others have gotten this working on linux, but i don't have it installed on my laptop so I'm not much help... all i can say is the package works fine in OSX & until another linux user chimes in, I've got to assume it works fine on other linux machines...

**Comment by Valentin-Seehausen** [comment]
No dont give me up :(
I deinstalled webpack globally, but it didnt help.

**Comment by Valentin-Seehausen** [comment]
I dont have any idea why it is not working, neither.

**Comment by CoveTechnologyAus** [comment]
Just noticed it doesn't build on Windows either. I think this is due to the NODE_ENV=*** in the package.json scripts. Windows requires SET NODE_ENV .......

**Comment by Valentin-Seehausen** [comment]
Nice, I am in a group with Windows-Users :)

But  `node ./src/server/server.babel.js` throws the same errors...

**Comment by CoveTechnologyAus** [comment]
@Valentin-Seehausen  my error is different to yours.
I think mine is purely because of the environment variable setting differences between OSX and Windows.
eg. My error is:

````
[0] 'NODE_ENV' is not recognized as an internal or external command,
[0] operable program or batch file.
````

**Comment by Valentin-Seehausen** [comment]
Anyway, good to have you here, @CoveTechnologyAus :)

Could it be that there is some issue with fsevents, because its for OSX? And I get a warn, too:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
```

**Comment by Valentin-Seehausen** [comment]
Maybe you could run something like `SET NODE_ENV=development node ./src/server/server.babel.js`

**Comment by CoveTechnologyAus** [comment]
These are just warnings and I think under OSX they can be ignored.
My build yesterday on OSX worked great and @mattkrick started looking at the size after my build issues.
Are you sure you are using the latest commit - maybe try pull it in again.

**Comment by CoveTechnologyAus** [comment]
@Valentin-Seehausen yeah that is what I have done.
And it builds great under windows now. I obviously can't run it as RethinkDB doesn't have a windows version but I wanted to test the build system under windows.

**Comment by Valentin-Seehausen** [comment]
Yes I am testing the latest commit. And now, where I change the webpack version to 1.12.0 it seems to be working.

**Comment by Valentin-Seehausen** [comment]
Ahja, but the Links are not working, console:
```
Unhandled promise rejection ReferenceError: System is not defined(…)(anonymous function) @ es6.promise.js:127
```

**Comment by CoveTechnologyAus** [comment]
I wonder if installing WebPack 2.0.1-beta globally will fix that (and change your package.json back).
Yesterday I had similar issues and only after installing WebPack globally did it resolve.
That's not to say that's what fixed it as @mattkrick was fixing lots of little things with the SSR implementation right around when I was trying to build.

**Comment by Valentin-Seehausen** [comment]
Hm. checkout aae1098 didnt work, neither, same errors. Webpack ^1.12.2 is used. Argh.

**Comment by mattkrick** [comment]
yeah, everything depends on webpack2. the joys of beta software :smile:

**Comment by Valentin-Seehausen** [comment]
Got it working!!!

So silly: There are two errors and why didn't I read them? It is said: "Cant find Module", and I had a look and the module "lostPassword.css" was not there, but "LostPassword.css" was there. Just renamend two or three files and meatier ist running like a charme. Nice work, @mattkrick . You can change the files (LostPassword and Lanes) or just merge my PR.

(I didnt open this thread, but conquered it, so for me it can be closes.)
