### ISSUE TITLE
Error keeps repeating on the server

### ISSUE THREAD

**Issue by babakness** [mattkrick/meatier#24]
I get this error
```
1450915130862 - Origin: Worker (PID 99729)
   [Error] Error: bind EADDRINUSE null:3000
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at cb (net.js:1296:16)
    at shared (cluster.js:582:5)
    at Worker.<anonymous> (cluster.js:556:9)
    at process.<anonymous> (cluster.js:710:8)
    at emitTwo (events.js:92:20)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at internal/child_process.js:496:7
    at process.handleConversion.net.Native.got (internal/child_process.js:43:7)
    at process.<anonymous> (internal/child_process.js:495:13)
    at emitTwo (events.js:92:20)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:438:11)
```
over and over on the server end.

**Comment by mattkrick** [comment]
you're running something else on port 3000. If you only use node you can enter `killall node` in your terminal & rerun. Or just restart your computer. Closing since it's not really meatier related.
