### ISSUE TITLE
EPEERINVALID on fresh clone and npm install

### ISSUE THREAD

**Issue by luandro** [mattkrick/meatier#26]
Just cloned and tried installing, but I get some `EPEERINVALID` errors. The first has to do with the history package, that was buggy in version 1.16.x, so you naturally set default to 1.13.x, but now the newer version of react-router requires version 1.17.x. Easy fix.

But the second `EPEERINVALID` error has to do with your redux-socket-cluster and socketcluster-client. Since I'm not familiar with these packages I don't know what's going on.

Cheers!

**Comment by mattkrick** [comment]
you sure those are errors & not warnings? Warnings are just an extra feature of using stuff in beta :wink:

**Comment by guilhermedecampo** [comment]
@mattkrick having the same problems!

here is the logs when I run `npm install` and after `npm run build`

using node v5.3.0!

```
meatier@0.5.0 /Users/Guilherme/Documents/Astrocoders/meatier
├─┬ babel-cli@6.3.17
│ └─┬ chokidar@1.4.1
│   └─┬ anymatch@1.3.0
│     └─┬ micromatch@2.3.7
│       └── kind-of@3.0.2
├── UNMET PEER DEPENDENCY history@1.13.1
├─┬ piping@0.3.0
│ └─┬ chokidar@1.4.1
│   └─┬ anymatch@1.3.0
│     └─┬ micromatch@2.3.7
│       └── kind-of@3.0.2
├── socketcluster-client@3.0.0  (git://github.com/mattkrick/socketcluster-client.git#90bbde5db8b26f2fba12daeacee93e29957b7c65)
└─┬ UNMET PEER DEPENDENCY webpack@2.0.1-beta
  └─┬ watchpack@0.2.9
    └─┬ chokidar@1.4.1
      └─┬ anymatch@1.3.0
        └─┬ micromatch@2.3.7
          ├─┬ braces@1.8.3
          │ └─┬ expand-range@1.8.1
          │   └─┬ fill-range@2.2.3
          │     ├─┬ is-number@2.1.0
          │     │ └── kind-of@3.0.2
          │     └─┬ randomatic@1.1.5
          │       └── kind-of@3.0.2
          └── kind-of@3.0.2

npm WARN EPEERINVALID babel-loader@6.2.0 requires a peer of webpack@^1.0.0 but none was installed.
npm WARN EPEERINVALID extract-text-webpack-plugin@0.9.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN EPEERINVALID react-router@1.0.3 requires a peer of history@^1.17.0 but none was installed.
npm WARN EPEERINVALID stats-webpack-plugin@0.2.2 requires a peer of webpack@^1.0 but none was installed.
npm WARN EPEERINVALID webpack-dev-middleware@1.4.0 requires a peer of webpack@>=1.0.0 <3 but none was installed.
➜  meatier git:(master) npm run build

> meatier@0.5.0 build /Users/Guilherme/Documents/Astrocoders/meatier
> rimraf build && concurrent "npm run build:client" "npm run build:server"

[0]
[0] > meatier@0.5.0 build:client /Users/Guilherme/Documents/Astrocoders/meatier
[0] > NODE_ENV=production webpack --colors --config ./webpack/prod.babel.js
[0]
[1]
[1] > meatier@0.5.0 build:server /Users/Guilherme/Documents/Astrocoders/meatier
[1] > NODE_ENV=production webpack --colors --config ./webpack/server.babel.js
[1]
[0] [BABEL] Note: The code generator has deoptimised the styling of "/Users/Guilherme/Documents/Astrocoders/meatier/node_modules/joi/node_modules/moment/moment.js" as it exceeds the max of "100KB".
[1] Hash: 5f4f01020a5ea4678ab8
[1] Version: webpack 2.0.1-beta
[1] Time: 59483ms
[1]     + 573 hidden modules
[1]
[1] ERROR in ./universal/redux/ducks/auth.js
[1] Module not found: Error: Cannot resolve module 'jwt-decode' in /Users/Guilherme/Documents/Astrocoders/meatier/src/universal/redux/ducks
[1]  @ ./universal/redux/ducks/auth.js 21:17-38
[1] Child extract-text-webpack-plugin:
[1]         + 2 hidden modules
[1] Child extract-text-webpack-plugin:
[1]         + 2 hidden modules
[1] Child extract-text-webpack-plugin:
[1]         + 2 hidden modules
[1] Child extract-text-webpack-plugin:
[1]         + 2 hidden modules
[1] Child extract-text-webpack-plugin:
[1]         + 2 hidden modules
[1] Child extract-text-webpack-plugin:
[1]         + 2 hidden modules
[1] Child extract-text-webpack-plugin:
[1]         + 2 hidden modules
[1] Child extract-text-webpack-plugin:
[1]         + 2 hidden modules
[1] Child extract-text-webpack-plugin:
[1]         + 3 hidden modules
[1] Child extract-text-webpack-plugin:
[1]         + 3 hidden modules
[1] Child extract-text-webpack-plugin:
[1]         + 5 hidden modules
[1] Child extract-text-webpack-plugin:
[1]         + 3 hidden modules
[1] Child extract-text-webpack-plugin:
[1]         + 3 hidden modules
[1] Child extract-text-webpack-plugin:
[1]         + 3 hidden modules
[1]
[1] npm
[1]
[1] ERR!
[1]  Darwin 15.2.0
[1] npm ERR!
[1]  argv "/Users/Guilherme/.nvm/v5.3.0/bin/node" "/Users/Guilherme/.nvm/v5.3.0/bin/npm" "run" "build:server"
[1] npm
[1]  ERR!
[1] node v5.3.0
[1] npm
[1]
[1] ERR! npm
[1]  v3.3.12
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! meatier@0.5.0 build:server: `NODE_ENV=production webpack --colors --config ./webpack/server.babel.js`
[1] npm ERR!
[1]  Exit status 2
[1] npm ERR!
[1]
[1] npm ERR! Failed at the meatier@0.5.0 build:server script 'NODE_ENV=production webpack --colors --config ./webpack/server.babel.js'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the meatier package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     NODE_ENV=production webpack --colors --config ./webpack/server.babel.js
[1] npm ERR! You can get their info via:
[1] npm ERR!     npm owner ls meatier
[1] npm ERR! There is likely additional logging output above.
[1]
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     /Users/Guilherme/Documents/Astrocoders/meatier/npm-debug.log
[1] npm run build:server exited with code 1
[0] Hash: f5afe5f989575c72608d
[0] Version: webpack 2.0.1-beta
[0] Time: 78995ms
[0]    [2] multi app 40 bytes {5} [built]
[0]    [3] multi vendor 112 bytes {4} [built]
[0]     + 905 hidden modules
[0]
[0] ERROR in ./universal/redux/ducks/auth.js
[0] Module not found: Error: Cannot resolve module 'jwt-decode' in /Users/Guilherme/Documents/Astrocoders/meatier/src/universal/redux/ducks
[0]  @ ./universal/redux/ducks/auth.js 21:17-38
[0]
[0] npm
[0]
[0] ERR!
[0]  Darwin 15.2.0
[0] npm
[0]  ERR! argv "/Users/Guilherme/.nvm/v5.3.0/bin/node" "/Users/Guilherme/.nvm/v5.3.0/bin/npm" "run" "build:client"
[0] npm
[0]  ERR!
[0] node
[0]  v5.3.0
[0] npm ERR!
[0]  npm  v3.3.12
[0] npm
[0]  ERR! code
[0]  ELIFECYCLE
[0] npm ERR!
[0]  meatier@0.5.0 build:client: `NODE_ENV=production webpack --colors --config ./webpack/prod.babel.js`
[0] npm ERR! Exit status 2
[0] npm ERR!
[0]
[0] npm ERR!
[0]  Failed at the meatier@0.5.0 build:client script 'NODE_ENV=production webpack --colors --config ./webpack/prod.babel.js'.
[0] npm ERR!
[0]  Make sure you have the latest version of node.js and npm installed.
[0] npm
[0] ERR! If you do, this is most likely a problem with the meatier package,
[0] npm
[0] ERR! not with npm itself.
[0] npm
[0] ERR! Tell the author that this fails on your system:
[0] npm
[0] ERR!     NODE_ENV=production webpack --colors --config ./webpack/prod.babel.js
[0] npm ERR!
[0]  You can get their info via:
[0] npm ERR!
[0]      npm owner ls meatier
[0] npm ERR!
[0]  There is likely additional logging output above.
[0]
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!     /Users/Guilherme/Documents/Astrocoders/meatier/npm-debug.log
[0] npm run build:client exited with code 1

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/Guilherme/.nvm/v5.3.0/bin/node" "/Users/Guilherme/.nvm/v5.3.0/bin/npm" "run" "build"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! meatier@0.5.0 build: `rimraf build && concurrent "npm run build:client" "npm run build:server"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meatier@0.5.0 build script 'rimraf build && concurrent "npm run build:client" "npm run build:server"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meatier package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf build && concurrent "npm run build:client" "npm run build:server"
npm ERR! You can get their info via:
npm ERR!     npm owner ls meatier
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Guilherme/Documents/Astrocoders/meatier/npm-debug.log
```

**Comment by mattkrick** [comment]
The error there is with jwt-decode, you sure you installed it?

**Comment by nickw** [comment]
I'm having the same issue. Here's my error log after cloning the repo and running `npm install`:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/opt/nvm/versions/node/v4.1.2/bin/node" "/usr/local/opt/nvm/versions/node/v4.1.2/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package socketcluster-client@3.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer redux-socket-cluster@0.3.1 wants socketcluster-client@git://github.com/mattkrick/socketcluster-client.git#master
```

**Comment by guilhermedecampo** [comment]
Yeah @mattkrick somehow jwt-decode was not installed when I ran `npm install`. 
But also after the build I had problems running `npm start` 

```
/Users/Guilherme/Documents/Astrocoders/meatier/src/server/init.js:3
    only(filename) {
        ^
SyntaxError: Unexpected token (
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Guilherme/Documents/Astrocoders/meatier/node_modules/ndata/server.js:20:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
1451186556151 - Origin: IOCluster
```
Already had this error before?

**Comment by mattkrick** [comment]
Closing, I think the resolution is to run a fresh install & ignore warnings. Reopen if this doesn't solve it.
