### ISSUE TITLE
UNMET PEER DEPENDENCY webpack@2.0.2-beta

### ISSUE THREAD

**Issue by smysnk** [mattkrick/meatier#96]
Doing npm install, 

```
$ npm install
amdefine@1.0.0 node_modules/react/node_modules/envify/node_modules/jstransform/node_modules/source-map/node_modules/amdefine -> node_modules/amdefine
asap@2.0.3 node_modules/react/node_modules/fbjs/node_modules/promise/node_modules/asap -> node_modules/asap
base62@0.1.1 node_modules/react/node_modules/envify/node_modules/jstransform/node_modules/base62 -> node_modules/base62
core-js@1.2.6 node_modules/graphql/node_modules/babel-runtime/node_modules/core-js -> node_modules/core-js
esprima-fb@13001.1001.0-dev-harmony-fb node_modules/react/node_modules/envify/node_modules/jstransform/node_modules/esprima-fb -> node_modules/esprima-fb
hoist-non-react-statics@1.0.5 node_modules/react-redux/node_modules/hoist-non-react-statics -> node_modules/hoist-non-react-statics
invariant@2.2.0 node_modules/react-redux/node_modules/invariant -> node_modules/invariant
promise@7.1.1 node_modules/react/node_modules/fbjs/node_modules/promise -> node_modules/promise
- js-tokens@1.0.2 node_modules/react-redux/node_modules/invariant/node_modules/loose-envify/node_modules/js-tokens
- loose-envify@1.1.0 node_modules/react-redux/node_modules/invariant/node_modules/loose-envify
- core-js@1.2.6 node_modules/react/node_modules/fbjs/node_modules/core-js
- js-tokens@1.0.2 node_modules/react/node_modules/fbjs/node_modules/loose-envify/node_modules/js-tokens
- loose-envify@1.1.0 node_modules/react/node_modules/fbjs/node_modules/loose-envify
source-map@0.1.31 node_modules/react/node_modules/envify/node_modules/jstransform/node_modules/source-map -> node_modules/source-map
jstransform@10.1.0 node_modules/react/node_modules/envify/node_modules/jstransform -> node_modules/jstransform
through@2.3.8 node_modules/react/node_modules/envify/node_modules/through -> node_modules/through
envify@3.4.0 node_modules/react/node_modules/envify -> node_modules/envify
ua-parser-js@0.7.10 node_modules/react/node_modules/fbjs/node_modules/ua-parser-js -> node_modules/ua-parser-js
whatwg-fetch@0.9.0 node_modules/react/node_modules/fbjs/node_modules/whatwg-fetch -> node_modules/whatwg-fetch
fbjs@0.6.1 node_modules/react/node_modules/fbjs -> node_modules/fbjs
meatier@0.9.0 /Users/josh/work/meatier
├─┬ eslint@2.2.0
│ └── lodash@4.5.1 
├── eslint-plugin-react@3.16.1 
├── graphql@0.4.18 
├── react@0.14.7 
├─┬ react-dnd@2.0.2
│ └─┬ dnd-core@1.3.0
│   ├── lodash@4.5.1 
│   └─┬ redux@3.3.1 
│     └── lodash@4.5.1 
├─┬ react-redux@4.4.0 
│ └── lodash@4.5.1 
├── redux@3.3.1 
└── UNMET PEER DEPENDENCY webpack@2.0.2-beta

npm WARN babel-loader@6.2.1 requires a peer of webpack@^1.0.0 but none was installed.
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN stats-webpack-plugin@0.3.0 requires a peer of webpack@^1.0 but none was installed.
npm WARN webpack-dev-middleware@1.4.0 requires a peer of webpack@>=1.0.0 <3 but none was installed.
```

Any ideas why?

**Comment by Bartekus** [comment]
Oh that's just a warning that you don't have globally installed Webpack,
However it's not necessery as it will work fine the way it is; installed locally. 

But if you insist:
>npm install -g webpack@2.0.2-beta

**Comment by smysnk** [comment]
Gotcha.

After running the quick start, next error I am seeing:
```
[3] Creating a pool connected to localhost:28015
[3] 1456389458830 - Origin: Worker (PID 3850)
[3]    [Error] Error: Module version mismatch. Expected 47, got 46.
[3]     at Error (native)
[3]     at Object.Module._extensions..node (module.js:440:18)
[3]     at Module.load (module.js:357:32)
[3]     at Function.Module._load (module.js:314:12)
[3]     at Module.require (module.js:367:17)
[3]     at require (internal/module.js:16:19)
[3]     at bindings (/Users/josh/work/meatier/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
[3]     at Object.<anonymous> (/Users/josh/work/meatier/node_modules/bcrypt/bcrypt.js:3:35)
[3]     at Module._compile (module.js:413:34)
[3]     at Module._extensions..js (module.js:422:10)
[3]     at Object.require.extensions.(anonymous function) [as .js] (/Users/josh/work/meatier/node_modules/babel-register/lib/node.js:138:7)
[3]     at Module.load (module.js:357:32)
[3]     at Function.Module._load (module.js:314:12)
[3]     at Module.require (module.js:367:17)
[3]     at require (internal/module.js:16:19)
[3]     at Object.<anonymous> (/Users/josh/work/meatier/src/server/graphql/models/User/userQuery.js:27:15)
[3] 1456389458865 - Worker 0 exited - Exit code: 1
```

**Comment by smysnk** [comment]
After rm -rf node_modules and fresh npm install, all is good. 

Thanks!

**Comment by jedwards1211** [comment]
@Bartekus what?  Are you saying there's such a thing as global peer dependencies?  I'm more inclined to believe it's this npm bug: https://github.com/npm/npm/issues/9857
